import { Geist, Geist_Mono, Sora, Solitreo, Solitreo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Copyright from "@/components/Copyright";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const solitreo = Solitreo({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-solitreo",
});

const sora = Sora({
  variable: "100 200 300 400 500 600 700 800",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} ${solitreo.variable} overflow-x-hidden bg-[#101311] relative antialiased`}
      >
        <Navbar />
        {children}
        <Copyright />
      </body>
    </html>
  );
}
